# Generated by Django 5.2.1 on 2025-05-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0003_planning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='description',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='title',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='planning',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du planning'),
        ),
        migrations.AddField(
            model_name='planning',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Session / Période'),
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
