# Generated by Django 5.2.1 on 2025-05-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0004_remove_lesson_classe_remove_lesson_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
