# Generated by Django 5.2.1 on 2025-05-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0006_planning_updated_at_classgroup_room_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='timetable_app.subject'),
        ),
    ]
